### ISSUE TITLE
Implement meta reading

### ISSUE THREAD

**Issue by isiahto** [isiahto/Jpegdecoder#1]
1. Read all markers into objects from 

- [x] Image meta pt.1 (`APP0`) (#2)

- [x] Image meta pt.2 (`SOF0`) (#3)

- [x] Table markers (`DHT`/`DQT) (#4)
